export const sliderData = [
  {
    title: 'First Game',
    image: require('../assets/images/homescreen/game-1.jpeg'),
  },
  {
    title: 'Second Game',
    image: require('../assets/images/homescreen/game-2.jpeg'),
  },
  {
    title: 'Third Game',
    image: require('../assets/images/homescreen/game-3.png'),
  },
];

export const paidGames = [
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'Spider-Man',
    subtitle: 'Marvel',
    isFree: 'No',
    price: '$25.99',
    id: '1',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Battlefield 2042',
    subtitle: 'EA',
    isFree: 'No',
    price: '$19.99',
    id: '2',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'Spider-Man: Miles Morales',
    subtitle: 'Marvel',
    isFree: 'No',
    price: '$29.99',
    id: '3',
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Halo Infinite',
    subtitle: 'Xbox Game',
    isFree: 'No',
    price: '$24.99',
    id: '4',
  },
  {
    poster: require('../assets/images/FarCry6.png'),
    title: 'Far Cry 6',
    subtitle: 'Ubisoft',
    isFree: 'No',
    price: '$15.99',
    id: '5',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'God of War: Ragnarok',
    subtitle: 'Sony',
    isFree: 'No',
    price: '$25.99',
    id: '6',
  },
];

export const freeGames = [
  {
    poster: require('../assets/images/Altos-Odyssey.jpeg'),
    title: 'Kalyan satta morning',
    subtitle: '299-01-669',
    isFree: 'No',
    id: '1',
    open: '09:30 AM',
    close: '10:30 AM',
  },
  {
    poster: require('../assets/images/asphalt-9.jpeg'),
    title: 'SriDevi Morning',
    subtitle: '140-51-119',
    isFree: 'No',
    id: '2',
    open: '09:35 AM',
    close: '10:35 AM',
  },
  {
    poster: require('../assets/images/genshin-impact.jpeg'),
    title: 'Milan Morning',
    subtitle: '889-58-170',
    isFree: 'No',
    id: '3',
    open: '10:10 AM',
    close: '11:10 AM',
  },
  {
    poster: require('../assets/images/fortnite.webp'),
    title: 'kalyan morning',
    subtitle: '129-22-228',
    isFree: 'No',
    id: '4',
    open: '10:55 AM',
    close: '11:55 AM',
  },
  {
    poster: require('../assets/images/pokemon-unite.jpeg'),
    title: 'Time bazar morning',
    subtitle: '128-79-126',
    isFree: 'No',
    id: '5',
    open: '11:10 AM',
    close: '12:10 PM',
  },
  {
    poster: require('../assets/images/diablo-4.jpeg'),
    title: 'madhur morning',
    subtitle: '279-80-460',
    isFree: 'No',
    id: '6',
    open: '11:25 AM',
    close: '12:25 PM',
  },
  {
    poster: require('../assets/images/spiderman.webp'),
    title: 'sridevi',
    subtitle: '179-05-447',
    isFree: 'No',
    id: '7',
    open: '11:30 AM',
    close: '12:30 PM',
  },
  {
    poster: require('../assets/images/battlefield-2042.webp'),
    title: 'Time bazar',
    subtitle: '115-72-390',
    isFree: 'No',
    id: '8',
    open: '01:00 PM',
    close: '02:00 PM',
  },
  {
    poster: require('../assets/images/miles-morales.webp'),
    title: 'madhur day',
    subtitle: '457-68-116',
    isFree: 'No',
    id: '9',
    open: '01:30 PM',
    close: '02:30 PM',
  },
  {
    poster: require('../assets/images/halo-infinite.jpeg'),
    title: 'Milan day',
    subtitle: '456-49-225',
    isFree: 'No',
    id: '10',
    open: '03:00 PM',
    close: '05:00 PM',
  },
  {
    poster: require('../assets/images/FarCry6.png'),
    title: 'rajdhani day',
    subtitle: '599-39-450',
    isFree: 'No',
    id: '11',
    open: '02:45 PM',
    close: '04:45 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'supreme day',
    subtitle: '339-56-899',
    isFree: 'No',
    id: '12',
    open: '03:25 PM',
    close: '05:25 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'Kalyan',
    subtitle: '450-96-349',
    isFree: 'No',
    id: '13',
    open: '03:45 PM',
    close: '05:45 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'sridevi night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '14',
    open: '07:00 PM',
    close: '08:00 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'mahdur night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '15',
    open: '08:15 PM',
    close: '10:15 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'supreme night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '16',
    open: '08:30 PM',
    close: '10:30 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'milan night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '17',
    open: '08:45 PM',
    close: '10:45 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'kalyan night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '18',
    open: '09:05 PM',
    close: '11:10 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'rajdhani night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '19',
    open: '09:10 PM',
    close: '11:20 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'kalyan satta night',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '20',
    open: '09:30 PM',
    close: '10:30 PM',
  },
  {
    poster: require('../assets/images/god-of-war.jpeg'),
    title: 'main bazar',
    subtitle: '***-**-***',
    isFree: 'Yes',
    id: '21',
    open: '09:35 PM',
    close: '11:55 PM',
  },
];